### ISSUE TITLE
function REGION END_REGION for TIA is not included

### ISSUE THREAD

**Issue by karelvl5** [Gunders89/vscode-scl#2]
function REGION END_REGION for TIA is not included

**Comment by Gunders89** [comment]
Hi

Thank you for taking your time to write an issue.

Region and end_region are included.
If your theme does not color it you can edit your theme to handle this:

1. Go to "User Settings"
2. Add this to your "User Settings" file:

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "entity.name.section.scl",
                "settings":{
                    "foreground": "#FF0000"
                }
            }
        ]
    } 
```

This will color region and end_region bright red. Change the color however you like by editing the value of the "foreground" property.
