### ISSUE TITLE
String escapement not working correctly

### ISSUE THREAD

**Issue by sikilde** [Gunders89/vscode-scl#21]
The new update doesn't give the correct result:
![image](https://github.com/user-attachments/assets/56d356d4-4f19-484c-99b5-1c8329b415e1)

Ref. https://github.com/Gunders89/vscode-scl/pull/17#pullrequestreview-2215730160
https://github.com/Gunders89/vscode-scl/pull/17#discussion_r1702269889

**Comment by Gunders89** [comment]
On my end it looks like this. 
![image](https://github.com/user-attachments/assets/b2d05e51-990c-4d1f-a3bc-514ff403356d)
Are you sure you're at v0.2.0?

**Comment by Gunders89** [comment]
![image](https://github.com/user-attachments/assets/dab77d6d-ba46-4e8b-b7b2-7e86034718cf)

**Comment by sikilde** [comment]
Indeed, it seems like I've tried with an older version. Sorry about that. 
![image](https://github.com/user-attachments/assets/36019fde-e4a6-40c4-b644-39229a5db665)
