### ISSUE TITLE
Will this plugin supports code-formating ?

### ISSUE THREAD

**Issue by Himmelt** [Gunders89/vscode-scl#7]

**Comment by Gunders89** [comment]
Good question, and I welcome the suggestion.

I have not given code formatting any thought as of yet. The possibility of adding code formatting will always be there, but my time is limited and right now I do not have the time to add that.

If code-formatting were to be introduced I'm pretty certain that there are a hundreds of opinions on how the code should be formatted. Maybe this should be discussed if it is to be implemented. 

It is, of course, possible for others to add code formatting to this repo, but I still believe a definition for how code should be formatted will have to be established first.
