### ISSUE TITLE
Instruction missing on how to compile and create manually installable extension from source

### ISSUE THREAD

**Issue by tamas-jaray** [Gunders89/vscode-scl#9]
I would like to ask you for a detailed instruction on how to create this extension from source and install it manually to VS Code.

I have made some changes to the snippets myself and I would like to contribute a little bit more by testing out my changes.
Fortunately I cant find the steps required to compile these sources and create a manually installable extension from these.

If you got the time and resources I would pretty much appreciate your help in advance.

**Comment by Gunders89** [comment]
Hi, I'm sorry for the late reply.

I believe you can clone the repo and then copy paste it into the Visual Studio Code package folder. 

There may be a better way of doing stuff nowadays. I recommend reading the documentation on package development which can be found  [here](https://code.visualstudio.com/api)
